name: Create GitHub release

permissions:
  contents: write

on:
  push:
    branches:
      - "viptela-vedge1000"
  schedule:
    # Build every week (sunday midnight)
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  release:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set outputs
        id: vars
        run: |
          echo "version_number=$(date +%Y-%m-%d).${{github.run_number}}" >> $GITHUB_OUTPUT

      - name: Setup toolchain
        id: toolchain
        run: |
          set -euo pipefail
          ver=$(curl -s https://downloads.openwrt.org/snapshots/targets/octeon/generic/sha256sums | awk '/openwrt-toolchain/ {print $2}' | sed -s 's/*//')
          echo "Latest toolchain available is ${ver}"
          curl "https://downloads.openwrt.org/snapshots/targets/octeon/generic/${ver}" -o toolchain.tar.zst
          mkdir -p toolchain/
          tar -C toolchain -xf toolchain.tar.zst '*/toolchain-*/' --strip-components=2
          rm -f toolchain.tar.zst
      - name: Setup build
        id: setup
        run: |
          set -euo pipefail
          set -x
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          cp -v sonix/diffconfig .config
          sed -i "s/SONIX-GIT/SONIX-${{ steps.vars.outputs.version_number }}/g" .config
          ./scripts/ext-toolchain.sh --toolchain $PWD/toolchain/ --overwrite-config --config octeon/generic
          if grep CONFIG_BUILD_NLS=y .config ; then echo '!!! We should not build with NLS as it increases build-time for no gain, remove it'; exit 1; fi
          make -j$(nproc) download
          make clean
      - name: Build the host tools
        id: host
        run: |
          make -j$(nproc) tools/compile
      - name: Build the target image
        id: build
        run: |
          make -j$(nproc) world || \
            (echo '!!! Failed, will retry twice more'; make -j$(nproc) world || \
            (echo '!!! Failed, will retry once more'; make -j$(nproc) world))
          cp -v .config bin/targets/octeon/generic/openwrt-octeon-generic-cisco_vedge1000.config
          cat bin/targets/octeon/generic/profiles.json | jq > bin/targets/octeon/generic/openwrt-octeon-generic-cisco_vedge1000.json
      - name: Print build times for packages
        id: buildtime
        if: always()
        run: |
          grep -h '^time: ' -r logs/ | cut -c 7- | sort -t '#' -n -k 4 | column -t -s '#' --table-columns PACKAGE,USER,SYSTEM,WALL
      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: logs
          path: logs/**
          if-no-files-found: error
          retention-days: 90
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: "v${{ steps.vars.outputs.version_number }}"
          prerelease: true
          tag_name: "v${{ steps.vars.outputs.version_number }}"
          target_commitish: "${{ github.sha }}"
          files: |
            bin/targets/octeon/generic/openwrt-*
