name: Create GitHub release

permissions:
  contents: write

on:
  push:
    branches:
      - "viptela-vedge1000"
  schedule:
    # Build every week (sunday midnight)
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  release:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set outputs
        id: vars
        run: |
          echo "version_number=$(date +%Y-%m-%d).${{github.run_number}}" >> $GITHUB_OUTPUT
      - name: Compile
        id: compile
        run: |
          set -euo pipefail
          set -x
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          cp -v sonix/diffconfig .config
          #for p in ./sonix/*.patch
          #do
          #  patch -p1 < $p
          #done
          sed -i "s/SONIX-GIT/SONIX-${{ steps.vars.outputs.version_number }}/g" .config
          make defconfig
          make -j$(nproc) download
          make clean
          make -j$(nproc) world || (echo '!!! Failed, rebuilding with verbose logs'; make world V=sc)
          cp -v .config bin/targets/octeon/generic/openwrt-octeon-generic-cisco_vedge1000.config
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: "v${{ steps.vars.outputs.version_number }}"
          prerelease: true
          tag_name: "v${{ steps.vars.outputs.version_number }}"
          files: |
            bin/targets/octeon/generic/openwrt-*
