# See https://openwrt.org/docs/guide-developer/feeds for syntax
src-git packages https://git.openwrt.org/feed/packages.git^b03e655bf02ec0eaf6a2bdbe5b1829d5e0b3710b
src-git luci https://git.openwrt.org/project/luci.git;master
src-git sonix https://github.com/sonix-network/openwrt-packages.git;master
